uclamii/model_tuner

- src/model_tuner/model_tuner_utils.py
- Reference before assignment bug fix in non-early stopping non score case
> Updating best_params: ref before assignment bug

- src/model_tuner/model_tuner_utils.py
- Changed 'layers' key to store count instead of list to avoid exceeding MLflow's 500-char limit.
- Simplified function by removing key filtering loop.
> Refactor summarize_auto_keras_params for MLflow logging

- notebooks/binary_debug.py
- src/model_tuner/model_tuner_utils.py
This PR enhances the stratification process by addressing two key issues: the handling of `stratify_cols` when it is `None` or a DataFrame, and the proper management of missing data in the stratification key. These changes make the code more robust and adaptable, ensuring it functions correctly even when the data is incomplete or when `stratify_cols` comes in different formats.
**Original Code:**
- The original code checks if `stratify_cols` and `stratify_y` are provided and truthy.
```python
if stratify_cols and stratify_y:
stratify_key = pd.concat([X[stratify_cols], y], axis=1)
elif stratify_cols:
stratify_key = X[stratify_cols]
elif stratify_y:
stratify_key = y
else:
stratify_key = None
```
- It concatenates the columns from `X_valid_test` based on `stratify_cols` with `y_valid_test` …
> Enhance stratification key handling with missing data and type checks

- .gitignore
- notebooks/xgb_early_bootstrap_test.py
- src/model_tuner/bootstrapper.py
> fixed bug, and added feature of class proportions boot sampling

- .gitignore
- src/model_tuner/model_tuner_utils.py
- Removed the following unused inputs:
```python
`X_train`, 
`y_train`,
`X_valid`,
```
- Added substantive docstring
> rem. unused inputs from tune_threshold_Fbeta(); updated docstring

- notebooks/bayesian_test.py
- src/model_tuner/model_tuner_utils.py
This allows us to set certain parameters in the bayesian search allowing the user to edit how many iterations are run etc.
> Bayesian update

- notebooks/bayesian_test.py
- notebooks/catboost_kfold.py
- src/model_tuner/model_tuner_utils.py
- Fixed kfold and bayesian `.fit()` methods
- A fitted model is now returned and can be used
- Bayesian parameters can be set as shown in the `bayesiantest.py`
- Remove unnecessary comments
- Moved to outside of the class
- Updated `stratify_y` to is not `None` to stop bugs
> Bayesian update train val test fix

- notebooks/xgb_early_smote_rfe_test.py
- RFE should always be instantiated using a model that has high regularisation
- Needs to also be updated in the documentation
> updating the way rfe is called so it uses elasticnet

- src/model_tuner/model_tuner_utils.py
- This is an aesthetic change. There was a badly formatted row of "=" we are just removing this so it looks cleaner.
> Removing a print in the pipeline steps

- notebooks/xgb_early_smote_rfe_test.py
- notebooks/xgb_early_test.py
- src/model_tuner/model_tuner_utils.py
- Imbalanced learning should now work with no other pipeline steps and with early stopping.
> SMOTE fix for early stopping

- .gitignore
- src/model_tuner/model_tuner_utils.py
- Needed to specify the pipeline class otherwise the method just returned a list
- Removed need to specify self.estimator when its called
> Feature selection pipeline extraction

- notebooks/adultincome_xgbearly.py
- src/model_tuner/model_tuner_utils.py
- Bug in early stopping caused by not setting X to X_train in the grid_search method.
> Early stopping Column Transformer fix 

- notebooks/multi_class_test.py
- notebooks/xgb_mutli.py
This branch contains two testing scripts that test the multiclass functionality of `model-tuner`. 
These scripts test:
- Random Forest
- XGBoost
> Multiclass Test Script

- unittests/test_model.py
Added tests for the following:
[ ] fit (PP)
[ ] get_best_score_params (PP)
[ ] return_bootstrap_metrics() (PP)
Test on Pp tests 2 branch first
> Pp tests 2

- py_example_scripts/catboost_kfold.py
- src/model_tuner/model_tuner_utils.py
- removed output_dict=True from kfold classification_report print
- updated docstrings for `return_metrics`, `return_metrics_kfold`, and `report_model_metrics`
- updated `tqdm` to output fold by fold in `report_model_metrics` when `print_per_fold=True` in `return_metrics`
- updated `catboost_kfold.py` to test above changes
> updated docs; tqdm for kfold, & output_dict

- src/model_tuner/model_tuner_utils.py
No codebase changes here -- just docstring additions to functions and methods that did not have them.
> added addtl' docstrings to methods/functions

- src/model_tuner/model_tuner_utils.py
Renaming imbalanced sampler method to match its functionality
> Changing imbalanced sampler method name

- unittests/test_model.py
print_selected_best_features(PP)
tune_threshold_Fbeta(PP)
conf_mat_class_kfold(PP)
Completed the above tests
Tests passed
> Pp tests ii

- unittests/test_model.py
Added the following tests:
Regression bootstrap metrics (PP)
predict - optimal_threshold = True (PP)
predict_proba - KFold and y is not None (PP)
Tests passed
> Pp tests iii

- unittests/test_model.py
Added the following tests that all pass:
- Fit an early boost model whilst specifying a score (PP)
- Fit an early boost model whilst specifying multiple scores (PP)
- Fit KFold model whilst specifying a score (PP)
- Fit KFold model whilst specifying multiple scores (PP)
- Fit an early boost model when a score is not specified (PP)
> Pp tests iv

- unittests/test_model.py
**Updated:**
- test_return_metrics_classification: Enhanced and refined the test logic for classification models to ensure comprehensive coverage of the return_metrics method.
**New Tests Added:**
- `test_return_metrics_multilabel_classification`: Introduced a new unittest to validate the functionality of `return_metrics` for multilabel classification models, including grid search and metric evaluation.
- `test_model_metrics_True_classification`: Added a test to specifically verify the behavior of `return_metrics` when `model_metrics=True` for classification models.
- `test_model_optimal_threshold_True_classification`: Added a test to validate the functionality of `return_metrics` with the `optimal_threshold` parameter set to `True`. This test ensures the metrics returned incorporate …
> updated bin class. test; (+) multilabel test

- unittests/test_model.py
These tests cover:
- regression_report - KFold case
- ColumnTransformer in pipeline
- Calibrate a model that uses imbalance sampling
- Extract different parts of the pipeline
> AF tests IV

- py_example_scripts/rf_kfold_calibrated.py
- src/model_tuner/model_tuner_utils.py
- Updated `print_threshold` logic to print the threshold that was previously not printing:
```python
if print_threshold:
print(f"Optimal threshold used: {threshold}")
```
> updated threshold print logic

- py_example_scripts/catboosttest.py
- unittests/test_model.py
The fix was already implemented so this branch contains tests covering this fix.
> Tests for feature selection pipeline

- unittests/test_model.py
Added following tests with and without kfold:
- test_grid_search_param_tuning_f1_beta_tune()
- test_grid_search_param_tuning_dataframe()
- test_grid_search_param_tuning_numpy()
- test_grid_search_param_tuning_kfold_dataframe_regression()
- test_grid_search_param_tuning_kfold_numpy_regression()
> Pp tests v

- py_example_scripts/xgb_early_smote_test.py
- py_example_scripts/xgbearly_calibrated_SHAP.py
- requirements.txt
- Removed extraneous `report_model_metrics` report from `xgb_early_smote_test.py` 
- Added SHAP explainer script here: `py_example_scripts/xgbearly_calibrated_SHAP.py`
- added `shap==0.46.0` to list of requirements in `requirements.txt`
> added shap script

- README_long.md
- src/model_tuner/model_tuner_utils.py
Removes deprecated `calibrate_report` code that is no longer used.
> Calibrate report remove

- unittests/test_model.py
Tests for early stopping fits with and without scores
> Adding tests for early stopping fit with and without a score

- py_example_scripts/threshold_testing_rf.py
- py_example_scripts/threshold_testing_xgb.py
- src/model_tuner/main.py
- src/model_tuner/threshold_optimization.py
- unittests/test_threshold_optimization.py
- Added new method for optimization threshold based on target precision
- Added `threshold_testing_rf.py` to test this method
- Added `test_threshold_optimization.py` inside unittests
> added new method and script for threshold optimization

- py_example_scripts/threshold_testing_rf.py
- src/model_tuner/threshold_optimization.py
- unittests/test_custom_help.py
- unittests/test_threshold_optimization.py
Added the option to specify a custom threshold range when tuning the thresholds. Still uses the original default value. Should perform exactly the same for all users who previously used this but will now have this extra custom option.
> Threshold Ranges in Threshold Optimisation

- src/model_tuner/bootstrapper.py
- unittests/test_bootstrapper.py
- unittests/test_custom_help.py
- Added support for multiple thresholds 
- Custom "average" parameter to choose which average when doing multi label bootstrapping
- Added support for hamming_loss
> Multi-Threshold Support to Bootstrapper
