- notebooks/binary_test.ipynb
- notebooks/xgb_early_test.py
- setup.py
- src/model_tuner/__init__.py
- src/model_tuner/model_tuner_utils.py
- Extract the number of estimators out of the xgboost model in early stopping case
- Add it back into the parameters to be used for fitting
> Fixing bug related to n_estimators not being used

- notebooks/binary_test.ipynb
- notebooks/regression_test.ipynb
- src/model_tuner/model_tuner_utils.py
**Description:**
Currently, the `train_val_test_split` method allows for stratification either by y (`stratify_y`) or by specified columns (`stratify_cols`), but not both at the same time. There are use cases where stratification by both the target variable (y) and specific columns is necessary to ensure a balanced and representative split across different data segments.
**Proposed Enhancement:**
Modify the method to support simultaneous stratification by both y and `stratify_cols`. This can be achieved by combining the stratification keys or implementing logic that ensures both y and the specified columns are considered during the stratification process.
**Current Method Implementation:**
```python
def train_val_test_split(
self,
X,
y,
stratify_y,
train_size,
validation_size,
test_size, …
```
> created todo comment for stratification fix

- src/model_tuner/model_tuner_utils.py
**Description:**
This pull request resolves the issue of misaligned **"Pos"** and **"Neg"** labels in the confusion matrix printout. The previous implementation incorrectly labeled the confusion matrix elements, leading to confusion in interpreting the results. This fix ensures that the labels correctly align with the corresponding values in the confusion matrix.
**Related Issue:**
Closes [Issue #32](https://github.com/uclamii/model_tuner/issues/32)
Previously, the constructor had the following labels:
```python
self.labels = ["tp", "fn", "fp", "tn"]
```
**Changes Made:**
- Updated the self.labels list to correctly reflect the confusion matrix elements
```python
self.labels = ["tn", "fp", "fn", "tp"]
```
- Modified the `_confusion_matrix_print` function to properly align the **"Pos"** and …
> corrected labels and pos args in conf_mat

- src/model_tuner/model_tuner_utils.py
- Fixing stratify cols bug: where y was used instead of `y_valid_test` causing length mismatch
- Catboost support added so that we can now use catboost early stopping (resetting estimators + try and except for catboost best iteration extraction) 
- Fixing ambiguity with the truth value of a list / dataframe error.
> Catboost support

- notebooks/catboosttest.py
- notebooks/xgb_early_test.py
- src/model_tuner/model_tuner_utils.py
This change was initiated due to an issue identified when running the `XGBoost` model in our pipeline. `XGBoost` does not require preprocessing steps like imputation or scaling, and as a result, it should be run without any pipeline steps in certain cases. However, a bug was discovered where the pipeline setup failed if no preprocessing steps were provided, leading to incorrect estimator initialization. To address this, a fix was implemented to handle scenarios where the pipeline might be empty, ensuring proper configuration of the estimator regardless of the preprocessing steps.
This PR fixes the initialization of the `pipeline_steps` and the assignment of the `estimator` in scenarios where the pipeline is provided and when it is not.
If `pipeline_steps` are provided (`self.pipeline == …
> Fix pipeline steps initialization and estimator setup for XGBoost compatibility

- notebooks/xgb_early_bootstrap_test.py
- requirements.txt
- setup.py
Updated the setup.py and requirements.txt to contain exact versions rather than anything above these versions. I think maybe we should include a range e.g. pandas 1.3.5 < pandas 2.2.2.
We can do this by changing the current fixed versions to this:
```pandas>=1.3.5,<2.2.2```
> Fixed Requirement Versions

- src/model_tuner/model_tuner_utils.py
This pull request enhances the `train_val_test_split` function by standardizing the handling of stratification parameters `stratify_y` and `stratify_cols`. Previously, passing `stratify_y=False` or `stratify_cols=False` did not disable stratification as users might expect. This fix ensures that both parameters interpret False as disabling stratification, thereby improving the function's usability and intuitiveness as follows:
```python
if stratify_y is False:
stratify_y = None
if stratify_cols is False:
stratify_cols = None
```
> added flexibility between bool and None for strat param

- src/model_tuner/model_tuner_utils.py
This pull request adds a custom exception to the `return_bootstrap_metrics` function to ensure users receive a clear and informative error message when passing `X_test` and `y_test` as data types other than pandas DataFrame or Series. Previously, providing inputs like `NumPy` arrays could result in confusing errors, making it difficult for users to identify the issue.
Added a type check at the beginning of the `return_bootstrap_metrics` function:
```python
if not isinstance(X_test, pd.DataFrame) or not isinstance(y_test, (pd.Series, pd.DataFrame)):
raise ValueError("Specifying X_test and/or y_test as anything other than pandas DataFrames is not supported.")
```
> Added Custom Exception for Non-Pandas Inputs in return_bootstrap_metrics

- src/model_tuner/model_tuner_utils.py
This PR enforces the specification of the `model_type` parameter (`classification` or `regression`) when creating an instance of the `Model` class. Previously, `model_type` defaulted to `"classification"`, but this could lead to unintended behavior if the user did not explicitly specify the type of model.
Removed Default Value for `model_type`:
- `model_type` is now a required parameter in the `__init__` method of the `Model` class. Users must specify it when instantiating the class.
- Added Validation Check for `model_type`:
- A simple `ValueError` is raised if `model_type` is not `"classification"` or `"regression"`, ensuring that the parameter is set to an accepted value.
```python
if model_type not in ["classification", "regression"]:
raise ValueError("You must specify model_type as …
```
> Enforce Required model_type Parameter in Model Class

- notebooks/lr_smote_test.py
- src/model_tuner/model_tuner_utils.py
Certain models, such as `XGBoost`, do not require imputation or scaling, making the inclusion of `pipeline_steps` unnecessary. However, omitting `pipeline_steps` while specifying an `imbalance_sampler` (e.g., SMOTE()) causes a `KeyError`, as shown below:
```python
KeyError: 'resampler'
```
**Proposed Solution**
Update the code logic to handle cases where pipeline_steps is omitted. Specifically:
1. Ensure `imbalance_sampler` functionality does not depend on the presence of `pipeline_steps`.
2. Add a check to gracefully handle scenarios where `pipeline_steps` is not explicitly provided.
> Handle Missing pipeline_steps When Using imbalance_sampler

- notebooks/xgb_early_test.py
The `xgb_early_test.py` script had an extra `model_type` input, so I removed it.
> removed extra input from xgb_early_test.py

- notebooks/early_stopping_coltrans.py
- notebooks/xgb_early_smote_rfe_test.py
- src/model_tuner/model_tuner_utils.py
Fixing issue #103. Bug caused by lack of validation data with early stopping when performing calibration.
Fix uses the validation data split we have already done in order to determine this. This should be the same as the data used in the previous fit and grid search.
> Fixing a bug found when calibrating early stopping models

- py_example_scripts/catboost_kfold.py
- py_example_scripts/lr_smote_test.py
- py_example_scripts/multi_class_test.py
- src/model_tuner/model_tuner_utils.py
- Added the `optimal_threshold=True` logic to `return_metrics`, allowing for custom thresholds to be used dynamically during predictions and evaluations.
- Ensured the threshold is printed at the end of execution if `print_threshold=True`.
- Enhanced k-fold handling to calculate and display both fold-specific metrics and average metrics across all folds.
- Metrics for each fold are printed in detail, followed by a summary of averaged metrics.
- Resolved the issue where non-numeric columns (`"Metric"`, `"Fold"`) caused aggregation errors during the `mean()` operation.
- Updated logic to only average numeric columns (`"Value"`) using `groupby("Metric")` for proper metric aggregation across folds.
- Introduced `metric_order` to ensure that metrics are displayed in a consistent and logical …
> Enhancements and Bug Fixes for Metric Reporting and Threshold Handling

- py_example_scripts/lr_smote_test.py
- py_example_scripts/regression_test_kfold.py
- src/model_tuner/model_tuner_utils.py
Part of this PR addresses a bug in the `return_metrics` function where the threshold was being printed even for regression models. Since thresholds are only applicable to classification models, this behavior has been corrected.
Thresholds are inherently tied to classification tasks where predictions are compared against a cutoff value. Printing a threshold for regression models is not relevant and could confuse users. This fix aligns the function's behavior with its intended purpose, improving its usability.
The updated logic ensures that:
- The threshold is printed only for classification models when `print_threshold=True`.
- For regression models, a message indicating that thresholds are not applicable is displayed.
Changes Made:
```python
if print_threshold:
if self.model_type != …
```
> Fix to Avoid Printing Threshold for Regression Models

- py_example_scripts/catboost_multi.py
- src/model_tuner/model_tuner_utils.py
- Added new `catboost_multi.py` script for testing multiclass Iris dataset w/ CatBoost algorithm. The code compiles.
- Added `model_metrics` print by specifying `True` for multiclass scenarios in `return_metrics` (simple fix):
```python
if model_metrics:
report_model_metrics(
self, X, y, threshold, True, print_per_fold
)
```
> CatBoost MultiClass Script and Multiclass Report Output Print

- .gitignore
- py_example_scripts/catboost_kfold.py
- src/model_tuner/model_tuner_utils.py
Currently, there is no visibility into the rebalanced class distribution during the KFold process. This enhancement improves user insight and debugging for imbalanced datasets. This change provides better transparency and debugging capability during the KFold process. It enhances the KFold implementation by adding a printout of the rebalanced class distribution when `imbalance_sampler` is used. 
Changes Made:
- Inserted print statements within the KFold loop to display the rebalanced class distribution after verifying the imbalance sampler:
```python
if self.imbalance_sampler:
self.verify_imbalance_sampler(X, y)
print(f"Rebalanced classes distribution: {dict(Counter(y))}")
```
Testing:
- Using `catboost_kfold.py` script, verified that the class distribution prints correctly for various …
> Add Printout of Rebalanced Classes in KFold Outputs

- src/model_tuner/model_tuner_utils.py
Previously, `return_metrics` returned `None` when setting `return_dict=True`. This has now been fixed by setting `report_model_metrics` to a new var `metrics` and updating the `return_dict` logic as follows:
```python
if model_metrics:
metrics = report_model_metrics(
self, X, y, threshold, True, print_per_fold
)
```
```python
if return_dict:
return metrics.set_index(["Class", "Metric"])["Value"].to_dict()
```
> Updated `return_dict` logic in `return_metrics`

- src/model_tuner/model_tuner_utils.py
- Expanded Handling for Multi-label Classification:
```python
print(
classification_report(
y,
y_pred_valid,
target_names=self.class_labels,
)
)
print("-" * 80)
```
- Instead of returning metrics directly, the new version:
- Stores the classification report in `self.classification_report`.
- Includes both the classification report and confusion matrix in the returned dictionary.
- This makes the output more comprehensive by including multiple metrics and results.
> updated dict logic in `return_metrics`

- src/model_tuner/model_tuner_utils.py
- Updated the second argument of `brier_score_loss` from `aggregated_y_pred` (predictions) to `aggregated_y_prob` (probabilities) as per the [documentation](https://scikit-learn.org/dev/modules/generated/sklearn.metrics.brier_score_loss.html).
```python
"Value": brier_score_loss(aggregated_y_true, aggregated_y_prob),
```
> Modified `aggregated_y_pred` to `aggregated_y_prob` inside `brier_score_loss`

- README.md
- pyproject.toml
- src/model_tuner/__init__.py
- src/model_tuner/model_tuner_utils.py
Simple patch that updates xgboost to match catboost behaviour when n_estimators is specified. We add 1 to the n_estimators variable as xgboost enumerates from 0.
> Xgboost n estimators fix

- README.md
- pyproject.toml
- src/model_tuner/__init__.py
- Updated to use pandas 2.2.2 if possible, this will make it more compatible with google colab.
> Google colab compatibility - pandas version

- py_example_scripts/early_cat_col_trans.py
- py_example_scripts/rf_calibrated.py
- src/model_tuner/model_tuner_utils.py
- Updated the `CalibratedClassifierCV` to fit on the validation set in two cases where `cv=prefit` is specified within the same block.
- Removed old (deprecated) commented out code in the `calibrateModel` method
- Added `rf`_calibrated_test.py` and `early_cat_col_trans.py` 
- All unit tests pass; none additional required
> upd. CalibratedClassifier to use validation set

- src/model_tuner/model_tuner_utils.py
This PR updates the docstring for the `stratify_y` parameter in the `train_val_test_split` function. The update clarifies that `stratify_y` should be a boolean (`True` or `None`), removing the previous reference to `pandas.Series`, which could cause errors.
**Updated docstring for `stratify_y`:**
```python
stratify_y : bool, optional
If True, stratifies based on the target variable (`y`).
If None or False, no stratification is applied.
Default is None.
```
- No functional code changes were made; only the documentation was updated.
- Existing functionality remains unchanged.
> Update docstring for `stratify_y` in `train_val_test_split`

- pyproject.toml
- Added upper bounds for all Python 3.7 dependencies (`<3.8`)
- Ensures compatibility by explicitly scoping packages to Python 3.7.x
> Upd. versioning for 3.7

- src/model_tuner/bootstrapper.py
- unittests/test_bootstrapper.py
In the evaluate_bootstrap_metrics function, switched the bootstrap branch from:
```python
y_pred_resample = model.predict(X_resample)
```
```python
y_pred_resample = model.predict(X_resample, optimal_threshold=True)
```
This ensures that during each resample we apply the model’s own optimal threshold (rather than a fixed 0.5) when turning probabilities into class labels.
- updated corresponding pytest
> Use model’s optimal threshold when predicting on bootstrap resamples
